### ISSUE TITLE
Can't save markdown file from dillinger to github

### ISSUE THREAD

**Issue by Xtina-R** [hist3907b-winter2015/module1-principlesofopenaccess#2]
I'm having major issues trying to get my exercise from dillinger into github. I have read the documentation but it absolutely does not make any sense to me as I know hardly any of the terminology. We have to request some type of authorization app, apparently, but I don't have a clue as to the various URLs  you have to provide and the 'secret'? This is way more tech-y than anything I've ever done before in my life. Some help would be awesome.

Hope this is the right place to post this; I'm still pretty confused about how to use Github in general.

**Comment by Xtina-R** [comment]
Never mind! Figured it out! Yay. Finally figured out how the windows interface works!

**Comment by shawngraham** [comment]
Hi! another possibility is [prose.io](http://prose.io) which plays more nicely with github. When you're trying to connect dillinger or prose to your github account, it needs your authentication (ie, your username and password) so it know which repository to connect to, and that you are who you say you are! Glad you got things sorted out; we'll talk more about github and how it works on wednesday.
